name: Android CI

on:
  push:
    branches: [ "*" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew build
    - name: Build debug apk
      run: ./gradlew assembleDebug
    - name: Upload debug apk
      uses: actions/upload-artifact@v3
      with:
        name: ${{ env.repository_name }}-${{ github.head_ref }}-${{ github.sha }}.apk
        path: ${{ env.main_project_module }}/build/outputs/apk/debug/